name: Multiline shell cmd
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run two cmd
        run: |
            echo "First ouput"
            echo "Second output"
